default_language_version:
  # default language version for each language
  python: python3.8
# fail_fast: true
repos:
  - repo: local
    hooks:
    - id: isort
      name: isort
      files: '^.*\.py$'
      language: system
      pass_filenames: true
      entry: isort
      exclude: ^migrations\.py$
    - id: black
      name: black
      files: '^.*\.py?$'
      language: system
      pass_filenames: true
      entry: black
      exclude: ^migrations\.py$
    - id: flake8
      name: flake8
      files: '^.*\.py?$'
      language: system
      pass_filenames: true
      entry: flake8
      exclude: ^migrations\.py$
